// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jurdhosifzgrssgcctyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1cmRob3NpZnpncnNzZ2NjdHlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MDA0MzUsImV4cCI6MjA2MzA3NjQzNX0.PuMF3-prOiUKPoC52QhmWZITu9gpxiO7GKAPITu_Fi8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);